import 'package:energy_meter_app/features/home_screen/providers/monthly_limit_provider.dart';
import 'package:energy_meter_app/features/routine/model/firebase_schedule_model.dart';
import 'package:energy_meter_app/features/routine/provider/firebase_schedule_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/services/energy_service.dart';
import '../model/suggestion_model.dart';

class SuggestionProvider extends ChangeNotifier {
  bool _isPanelVisible = false;
  bool get isPanelVisible => _isPanelVisible;
  final EnergyService _energyService;
  final MonthlyLimitProvider _monthlyLimitProvider;

  Suggestion? _suggestion;
  Suggestion? get suggestion => _suggestion;

  SuggestionProvider(this._energyService, this._monthlyLimitProvider) {
    _energyService.addListener(_updateSuggestions);
    _monthlyLimitProvider.addListener(_updateSuggestions);
    _updateSuggestions();
  }

  void _updateSuggestions() {
    final currentUsage = _monthlyLimitProvider.currentUsage;
    final monthlyLimit = _monthlyLimitProvider.limit;

    debugPrint('[SuggestionProvider] Checking for suggestions...');
    debugPrint('[SuggestionProvider] Consumption: $currentUsage, Limit: $monthlyLimit');

    if (monthlyLimit > 0 && currentUsage > (monthlyLimit * 0.8)) {
      if (_suggestion == null) {
        debugPrint('[SuggestionProvider] THRESHOLD EXCEEDED. Creating new suggestion.');
        _suggestion = Suggestion(
          title: 'Energy Saving Tip',
          description:
              'You can save energy by turning off the Smart AC between 2 PM and 5 PM.',
          deviceId: 'Smart AC',
          action: 'schedule_off',
        );
        notifyListeners();
      }
    } else {
      if (_suggestion != null) {
        debugPrint('[SuggestionProvider] Consumption below threshold. Clearing suggestion.');
        _suggestion = null;
        notifyListeners();
      }
    }
  }

  @override
  void dispose() {
    _energyService.removeListener(_updateSuggestions);
    _monthlyLimitProvider.removeListener(_updateSuggestions);
    super.dispose();
  }

  void togglePanel() {
    _isPanelVisible = !_isPanelVisible;
    notifyListeners();
  }

  void dismissSuggestion() {
    _suggestion = null;
    // Keep the panel open briefly to show the result, then it will disappear.
    notifyListeners();
  }

  Future<void> applySuggestion(BuildContext context) async {
    if (_suggestion == null) return;

    final scheduleProvider = context.read<FirebaseScheduleProvider>();

    // Simple mapping from device name to relay number. This can be improved later.
    final Map<String, int> deviceToRelayMap = {'Smart AC': 4};

    final relayNumber = deviceToRelayMap[_suggestion!.deviceId];
    if (relayNumber == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Error: Device not found.')));
      return;
    }

    final startTime = const TimeOfDay(hour: 14, minute: 0);
    final endTime = const TimeOfDay(hour: 17, minute: 0);

    final newSchedule = FirebaseSchedule(
      id: '', // ID will be generated by Firebase
      relay: relayNumber,
      action: 'OFF', // The suggestion is to turn the device OFF
      startTime:
          '${startTime.hour.toString().padLeft(2, '0')}:${startTime.minute.toString().padLeft(2, '0')}',
      endTime:
          '${endTime.hour.toString().padLeft(2, '0')}:${endTime.minute.toString().padLeft(2, '0')}',
      enabled: true,
    );

    try {
      await scheduleProvider.createSchedule(newSchedule);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Energy-saving tip applied successfully!'),
        ),
      );
      dismissSuggestion();
      togglePanel();
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to apply tip: $e')));
    }
  }
}
