// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvuoZAlKpFFOwRF333Oycn6aFZVPk9js',
    appId: '1:884026744808:web:03f0cac8c0fd32e5078e5d',
    messagingSenderId: '884026744808',
    projectId: 'energypulse-e24dc',
    authDomain: 'energypulse-e24dc.firebaseapp.com',
    databaseURL: 'https://energypulse-e24dc-default-rtdb.firebaseio.com',
    storageBucket: 'energypulse-e24dc.firebasestorage.app',
    measurementId: 'G-NF8BKGSZ1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHom8sEqbPsvHYCd3CN1lmqwESNw6ZlY',
    appId: '1:884026744808:android:16c62750b74ab175078e5d',
    messagingSenderId: '884026744808',
    projectId: 'energypulse-e24dc',
    databaseURL: 'https://energypulse-e24dc-default-rtdb.firebaseio.com',
    storageBucket: 'energypulse-e24dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVr5ZQBekO3ZeskcJm9wtNrKdqpYSxqJ8',
    appId: '1:884026744808:ios:bd6e231dae01f3b1078e5d',
    messagingSenderId: '884026744808',
    projectId: 'energypulse-e24dc',
    databaseURL: 'https://energypulse-e24dc-default-rtdb.firebaseio.com',
    storageBucket: 'energypulse-e24dc.firebasestorage.app',
    iosBundleId: 'com.example.energyMeterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVr5ZQBekO3ZeskcJm9wtNrKdqpYSxqJ8',
    appId: '1:884026744808:ios:bd6e231dae01f3b1078e5d',
    messagingSenderId: '884026744808',
    projectId: 'energypulse-e24dc',
    databaseURL: 'https://energypulse-e24dc-default-rtdb.firebaseio.com',
    storageBucket: 'energypulse-e24dc.firebasestorage.app',
    iosBundleId: 'com.example.energyMeterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcvuoZAlKpFFOwRF333Oycn6aFZVPk9js',
    appId: '1:884026744808:web:fcb2a74151d201fa078e5d',
    messagingSenderId: '884026744808',
    projectId: 'energypulse-e24dc',
    authDomain: 'energypulse-e24dc.firebaseapp.com',
    databaseURL: 'https://energypulse-e24dc-default-rtdb.firebaseio.com',
    storageBucket: 'energypulse-e24dc.firebasestorage.app',
    measurementId: 'G-JFEZ7F0MJF',
  );
}
